package models;
// Generated 14 janv. 2016 11:13:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Aeroport generated by hbm2java
 */
public class Aeroport implements java.io.Serializable {

	private Integer idAeroport;
	private Ville ville;
	private String nom;
	private String code;
	private Set volsForIdAeroportDepart = new HashSet(0);
	private Set volsForIdAeroportArrivee = new HashSet(0);

	public Aeroport() {
	}

	public Aeroport(Ville ville) {
		this.ville = ville;
	}

	public Aeroport(Ville ville, String nom, String code, Set volsForIdAeroportDepart, Set volsForIdAeroportArrivee) {
		this.ville = ville;
		this.nom = nom;
		this.code = code;
		this.volsForIdAeroportDepart = volsForIdAeroportDepart;
		this.volsForIdAeroportArrivee = volsForIdAeroportArrivee;
	}

	public Integer getIdAeroport() {
		return this.idAeroport;
	}

	public void setIdAeroport(Integer idAeroport) {
		this.idAeroport = idAeroport;
	}

	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set getVolsForIdAeroportDepart() {
		return this.volsForIdAeroportDepart;
	}

	public void setVolsForIdAeroportDepart(Set volsForIdAeroportDepart) {
		this.volsForIdAeroportDepart = volsForIdAeroportDepart;
	}

	public Set getVolsForIdAeroportArrivee() {
		return this.volsForIdAeroportArrivee;
	}

	public void setVolsForIdAeroportArrivee(Set volsForIdAeroportArrivee) {
		this.volsForIdAeroportArrivee = volsForIdAeroportArrivee;
	}

}
