package models;
// Generated 13 janv. 2016 15:16:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Avion generated by hbm2java
 */
public class Avion implements java.io.Serializable {

	private Integer idAvion;
	private String matricule;
	private Integer nbPlace;
	private String type;
	private Set vols = new HashSet(0);

	public Avion() {
	}

	public Avion(String matricule, Integer nbPlace, String type, Set vols) {
		this.matricule = matricule;
		this.nbPlace = nbPlace;
		this.type = type;
		this.vols = vols;
	}

	public Integer getIdAvion() {
		return this.idAvion;
	}

	public void setIdAvion(Integer idAvion) {
		this.idAvion = idAvion;
	}

	public String getMatricule() {
		return this.matricule;
	}

	public void setMatricule(String matricule) {
		this.matricule = matricule;
	}

	public Integer getNbPlace() {
		return this.nbPlace;
	}

	public void setNbPlace(Integer nbPlace) {
		this.nbPlace = nbPlace;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getVols() {
		return this.vols;
	}

	public void setVols(Set vols) {
		this.vols = vols;
	}

}
