package models;
// Generated 14 janv. 2016 11:13:46 by Hibernate Tools 3.4.0.CR1

/**
 * EtapeId generated by hbm2java
 */
public class EtapeId implements java.io.Serializable {

	private int idReservation;
	private int idVol;

	public EtapeId() {
	}

	public EtapeId(int idReservation, int idVol) {
		this.idReservation = idReservation;
		this.idVol = idVol;
	}

	public int getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(int idReservation) {
		this.idReservation = idReservation;
	}

	public int getIdVol() {
		return this.idVol;
	}

	public void setIdVol(int idVol) {
		this.idVol = idVol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtapeId))
			return false;
		EtapeId castOther = (EtapeId) other;

		return (this.getIdReservation() == castOther.getIdReservation()) && (this.getIdVol() == castOther.getIdVol());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdReservation();
		result = 37 * result + this.getIdVol();
		return result;
	}

}
