package models;
// Generated 13 janv. 2016 15:16:17 by Hibernate Tools 3.4.0.CR1

/**
 * Passager generated by hbm2java
 */
public class Passager implements java.io.Serializable {

	private Integer idPassager;
	private Reservation reservation;
	private String nom;
	private String categorie;

	public Passager() {
	}

	public Passager(Reservation reservation) {
		this.reservation = reservation;
	}

	public Passager(Reservation reservation, String nom, String categorie) {
		this.reservation = reservation;
		this.nom = nom;
		this.categorie = categorie;
	}

	public Integer getIdPassager() {
		return this.idPassager;
	}

	public void setIdPassager(Integer idPassager) {
		this.idPassager = idPassager;
	}

	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

}
