package models;
// Generated 13 janv. 2016 15:16:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays implements java.io.Serializable {

	private Integer idPays;
	private String code;
	private String nom;
	private Set villes = new HashSet(0);

	public Pays() {
	}

	public Pays(String code, String nom, Set villes) {
		this.code = code;
		this.nom = nom;
		this.villes = villes;
	}

	public Integer getIdPays() {
		return this.idPays;
	}

	public void setIdPays(Integer idPays) {
		this.idPays = idPays;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Set getVilles() {
		return this.villes;
	}

	public void setVilles(Set villes) {
		this.villes = villes;
	}

}
