package models;
// Generated 14 janv. 2016 11:13:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer idReservation;
	private Client client;
	private Date dateDepart;
	private Date dateRetour;
	private String classe;
	private Set etapes = new HashSet(0);
	private Set passagers = new HashSet(0);

	public Reservation() {
	}

	public Reservation(Client client) {
		this.client = client;
	}

	public Reservation(Client client, Date dateDepart, Date dateRetour, String classe, Set etapes, Set passagers) {
		this.client = client;
		this.dateDepart = dateDepart;
		this.dateRetour = dateRetour;
		this.classe = classe;
		this.etapes = etapes;
		this.passagers = passagers;
	}

	public Integer getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(Integer idReservation) {
		this.idReservation = idReservation;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	public Date getDateRetour() {
		return this.dateRetour;
	}

	public void setDateRetour(Date dateRetour) {
		this.dateRetour = dateRetour;
	}

	public String getClasse() {
		return this.classe;
	}

	public void setClasse(String classe) {
		this.classe = classe;
	}

	public Set getEtapes() {
		return this.etapes;
	}

	public void setEtapes(Set etapes) {
		this.etapes = etapes;
	}

	public Set getPassagers() {
		return this.passagers;
	}

	public void setPassagers(Set passagers) {
		this.passagers = passagers;
	}

}
