package models;
// Generated 14 janv. 2016 11:13:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vol generated by hbm2java
 */
public class Vol implements java.io.Serializable {

	private Integer idVol;
	private Aeroport aeroportByIdAeroportArrivee;
	private Avion avion;
	private Aeroport aeroportByIdAeroportDepart;
	private Date dateDepart;
	private Date dateArrive;
	private Date heureDepart;
	private Date heureArrivee;
	private Integer nbPlaceReservee;
	private Integer prix;
	private Set etapes = new HashSet(0);



	public Vol() {
	}

	public Vol(Aeroport aeroportByIdAeroportArrivee, Avion avion, Aeroport aeroportByIdAeroportDepart) {
		this.aeroportByIdAeroportArrivee = aeroportByIdAeroportArrivee;
		this.avion = avion;
		this.aeroportByIdAeroportDepart = aeroportByIdAeroportDepart;
	}

	public Vol(Aeroport aeroportByIdAeroportArrivee, Avion avion, Aeroport aeroportByIdAeroportDepart, Date dateDepart,
			Date dateArrive, Date heureDepart, Date heureArrivee, Integer nbPlaceReservee, Integer prix, Set etapes) {
		this.aeroportByIdAeroportArrivee = aeroportByIdAeroportArrivee;
		this.avion = avion;
		this.aeroportByIdAeroportDepart = aeroportByIdAeroportDepart;
		this.dateDepart = dateDepart;
		this.dateArrive = dateArrive;
		this.heureDepart = heureDepart;
		this.heureArrivee = heureArrivee;
		this.nbPlaceReservee = nbPlaceReservee;
		this.prix = prix;
		this.etapes = etapes;
	}

	public Integer getIdVol() {
		return this.idVol;
	}

	public void setIdVol(Integer idVol) {
		this.idVol = idVol;
	}

	public Aeroport getAeroportByIdAeroportArrivee() {
		return this.aeroportByIdAeroportArrivee;
	}

	public void setAeroportByIdAeroportArrivee(Aeroport aeroportByIdAeroportArrivee) {
		this.aeroportByIdAeroportArrivee = aeroportByIdAeroportArrivee;
	}

	public Avion getAvion() {
		return this.avion;
	}

	public void setAvion(Avion avion) {
		this.avion = avion;
	}

	public Aeroport getAeroportByIdAeroportDepart() {
		return this.aeroportByIdAeroportDepart;
	}

	public void setAeroportByIdAeroportDepart(Aeroport aeroportByIdAeroportDepart) {
		this.aeroportByIdAeroportDepart = aeroportByIdAeroportDepart;
	}

	public Date getDateDepart() {
		return this.dateDepart;
	}

	public void setDateDepart(Date dateDepart) {
		this.dateDepart = dateDepart;
	}

	public Date getDateArrive() {
		return this.dateArrive;
	}

	public void setDateArrive(Date dateArrive) {
		this.dateArrive = dateArrive;
	}

	public Date getHeureDepart() {
		return this.heureDepart;
	}

	public void setHeureDepart(Date heureDepart) {
		this.heureDepart = heureDepart;
	}

	public Date getHeureArrivee() {
		return this.heureArrivee;
	}

	public void setHeureArrivee(Date heureArrivee) {
		this.heureArrivee = heureArrivee;
	}

	public Integer getNbPlaceReservee() {
		return this.nbPlaceReservee;
	}

	public void setNbPlaceReservee(Integer nbPlaceReservee) {
		this.nbPlaceReservee = nbPlaceReservee;
	}

	public Set getEtapes() {
		return this.etapes;
	}

	public void setEtapes(Set etapes) {
		this.etapes = etapes;
	}

	public Integer getPrix() {
		return prix;
	}

	public void setPrix(Integer prix) {
		this.prix = prix;
	}

}
